workflows:
  ios-build:
    name: Vibeflix
    max_build_duration: 60
    environment:
      cocoapods: default
    xcode: latest  # of specificeer een specifieke Xcode-versie, bv. 14.0
    scripts:
      - name: Install dependencies
        script: |
          pod install --repo-update
      - name: Run Tests
        script: |
          xcodebuild test -workspace Vibeflix.xcworkspace -scheme VibeflixScheme -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty
    artifacts:
      - build/Vibeflix.ipa
    publishing:
      email:
        recipients:
          - help.vibeflix@gmail.com